## Numpy
```
Numerical Python
고성능 수치 계산을 위한 라이브러리
백터나 행렬 연산에 편리한 기능 제공
모든 원소는 같은 자료형만 가능
```

In [10]:
import numpy as np
a = np.arange( 15 )
print( a )
a = a.reshape( 3, 5 )
print ( a )
print ( type ( a ) )
print ( a.shape )
print ( a.dtype )
print ( a.ndim )

# print ( dir(np) )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
(3, 5)
int32
2


```
객체 = class
print ( type ( a ) ) = type 확인 가능
ctrl + / 주석처리 가능
```

In [11]:
print ( a )

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
f = np.array( [0, 1], [1, 1] )
g = np.array( [2, 0], [3, 4] )
print ( f * g )                   # 행렬곱
print ( f @ g )
print ( np.dot (f, g) )
print ( f.dot (f, g) )

NameError: name 'np' is not defined

In [8]:
h = np.zeros (10)
print(h)
# i = np.zeros (5, 5) 보통 행과 열의 조합으로 짜는데 zeros는 튜플로 들어가야 함
i = np.zeros((5,5))
print = i
j = np.ones(10) #ones는 모두 1로 채움
print = (j) 

# tab / shift + tap 단락 들여쓰기 지우기

# np.random.random    0~1 사이의 난수 발생
# np.random.randint   균일 분포의 정수 난수 발생
# np.random.rand      0~1 사이의 균일 분포 난수 matrix array 생성
# np.random.randn     가우시안 표준 정규 분포 난수 matrix array 생성
# np.random.nomral    평균, 표준편차, sample 개수

k = np.random.random(10) * 100
print(type(k))
print(k)

print(np.random.randint(10))
print(np.random.rand(5, 2))

NameError: name 'np' is not defined

In [1]:
conda create -n my-env

error: incomplete escape \U at position 28